# !!!This only applies to worlds being handled by Multiverse!!!
# If you don't see it using /mvlist this setting WILL HAVE NO EFFECT
# Valid values are:
# all: If you die in a Nether an attempt will be made to spawn you in the corresponding Normal world, if not you go to defaultspawnworld
# default: If you die in a Nether you will respawn in the world defined below in defaultspawnworld
# none: You will always respawn in the same world you died in
notchrespawnstyle: none

#
defaultspawnworld: world

# How long to leave in between sending a message to the player.
# In Milliseconds - Default is '5000' which is 5 Seconds.
messagecooldown: 5000

# Portal Cooldown, only affects MultiVerse portals.
# In Milliseconds - Default is '5000' which is 5 Seconds.
portalcooldown: 5000

# If this is set to true, we will prefix the chat with 
# a colorful world alias if it's present. If not, we simply
# show the world's name in white. If this is false Multiverse
# won't touch your chat
worldnameprefix: true

# If Multiverse does not find permissions should it automatically fall back to
# people defined in ops.txt? Remember, if you use ops based permissions
# the awesome Multiverse devs get to decide which commands require op!
# (Which is why we highly recommend a permissions plugin! You shouldn't trust us this much...)
opfallback: true


# If you have a world(s) that has monsters = false, and you want to disable the built
# in autohealing, set this to true. This will have NO EFFECT if monsters = true for a given world. 
disableautoheal: false