name: MultiVerse-Core
main: com.onarandombox.MultiVerseCore.MultiVerseCore
authors: ['Rigby','Protected']
version: 2.0
commands:
  mvcreate:
    description: World create command
    usage: |
            /<command> <world> <environment>
            /<command> creative normal -- Creates a world called 'creative' with a NORMAL environment.
            /<command> hellworld nether -- Creates a world called 'hellworld' with a NETHER environment.
  mvimport:
    description: World import command
    usage: |
            /<command> <world> <environment>
            /<command> creative normal -- Imports an existing world called 'creative' with a NORMAL environment.
            /<command> hellworld nether -- Imports an existing world called 'hellworld' with a NETHER environment.
  mvremove:
    description: World delete command
    usage: |
            /<command> <world>
            /<command> creative -- Removes the world 'creative' from the MultiVerse setup.
            /<command> hellworld -- Removes the world 'hellworld' from the MultiVerse setup.
  mvmodify:
    description: Modify the settings of an existing world
    usage: |
            /<command> <world> <option>:<value>
            /<command> creative pvp:false -- Turns off PVP in the 'creative' world.
  mvtp:
    description: Command to teleport between Worlds
    usage: |
            /<command> <world>[:spawn]
            Example: /<command> creative - Teleports you to the relevant location in the 'creative' world.
            Example: /<command> creative:spawn - Teleports you to the spawn of the 'creative' world.
  mvlist:
    description: Print list of loaded Worlds
    usage: |
            /<command> [environment]
            Example: /<command> NETHER - Shows all NETHER Worlds.
            Example: /<command> NORMAL - Shows all NORMAL Worlds. 
  mvsetspawn:
    description: Set the spawn area for a particular world
    usage: /<command> -- Sets the spawn area of the current world to your location.
  mvspawn:
    description: Teleport to the spawn area
    usage: /<command> -- Teleports you to the spawn area of your current world.
  mvcoord:
    description: Display World, Coordinates, Direction & Compression for a world.
    usage: |
            /<command> [world]
            /<command> -- Shows the relevant coordinates in your current world. 
            /<command> creative -- Shows the relevant coordinates if you were in the 'creative' world.
  mvwho:
    description: Display online users per world.
    usage: |
            /<command> [world]
            /<command> -- Shows who is online in each world.
            /<command> creative -- Shows who is online in the 'creative' world.
  mvreload:
    description: Reload Configuration files.
    usage: /<command>
  mvpurge:
    description: Purge the targetted world of creatures.
    usage: |
            /<command> [world] [creatures]
            /<command> -- Purges the players world of all creatures.
            /<command> creative * -- Purges the creative world of all Creatures.
            /<command> creative creeper -- Purges the creative world of all CREEPERS.